CREATE DATABASE `SHOPPINGCART` CHARACTER SET utf8 COLLATE utf8_general_ci; 

USE SHOPPINGCART
CREATE TABLE CATEGORY
(
CategoryId INT PRIMARY KEY AUTO_INCREMENT,
CategoryName VARCHAR(255),
CategoryDescription TEXT 
)
CREATE TABLE PRODUCTS
(
ProductId INT PRIMARY KEY AUTO_INCREMENT,
ProductName VARCHAR(255),
ProductDetails VARCHAR(255),
ProductsUpdate DATE,
CategoryId INT,
FOREIGN KEY (CategoryId) REFERENCES category(CategoryId)
)